export enum AuditActionType {
  RECEIVABLE_CREATE = 'RECEIVABLE_CREATE',
  RECEIVABLE_UPDATE = 'RECEIVABLE_UPDATE',
  RECEIVABLE_WRITE_OFF = 'RECEIVABLE_WRITE_OFF',
  RECEIVABLE_CANCEL = 'RECEIVABLE_CANCEL',
  RECEIVABLE_DISPUTE = 'RECEIVABLE_DISPUTE',
  PAYMENT_ALLOCATE = 'PAYMENT_ALLOCATE',
  PAYMENT_ALLOCATE_UNDO = 'PAYMENT_ALLOCATE_UNDO',
  REMINDER_POLICY_UPDATE = 'REMINDER_POLICY_UPDATE',
  BANK_CONNECTION_CREATE = 'BANK_CONNECTION_CREATE',
  BANK_CONNECTION_DISCONNECT = 'BANK_CONNECTION_DISCONNECT',
  SUBSCRIPTION_CHANGE_PLAN = 'SUBSCRIPTION_CHANGE_PLAN',
  BANK_TRANSACTION_SKIP = 'BANK_TRANSACTION_SKIP',
  BANK_TRANSACTION_MARK_PREPAID = 'BANK_TRANSACTION_MARK_PREPAID',
}

export enum AuditEntityType {
  RECEIVABLE = 'Receivable',
  PAYMENT = 'Payment',
  PAYMENT_ALLOCATION = 'PaymentAllocation',
  BANK_TRANSACTION = 'BankTransaction',
  REMINDER_POLICY = 'ReminderPolicy',
  BANK_CONNECTION = 'BankConnection',
  SUBSCRIPTION = 'Subscription',
}
