export enum LedgerEventKind {
  RECEIVABLE_CREATED = 'RECEIVABLE_CREATED',
  RECEIVABLE_ALLOCATED = 'RECEIVABLE_ALLOCATED',
  RECEIVABLE_ALLOCATION_UNDONE = 'RECEIVABLE_ALLOCATION_UNDONE',
  RECEIVABLE_CANCELLED = 'RECEIVABLE_CANCELLED',
  RECEIVABLE_WRITTEN_OFF = 'RECEIVABLE_WRITTEN_OFF',
  RECEIVABLE_ROLLOUT_BASELINE = 'RECEIVABLE_ROLLOUT_BASELINE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_ALLOCATED = 'PAYMENT_ALLOCATED',
  PAYMENT_ALLOCATION_UNDONE = 'PAYMENT_ALLOCATION_UNDONE',
  PAYMENT_ROLLOUT_BASELINE = 'PAYMENT_ROLLOUT_BASELINE',
}
