export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  TENANT_MISMATCH = 'TENANT_MISMATCH',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
