export const ENTITY_TYPE_LABELS: Record<string, string> = {
  Receivable: 'Khoản phải thu',
  Payment: 'Thanh toán',
  PaymentAllocation: 'Phân bổ thanh toán',
  BankTransaction: 'Giao dịch ngân hàng',
  ReminderPolicy: 'Chính sách nhắc',
  BankConnection: 'Kết nối ngân hàng',
  CassoFlowAuthorization: 'Ủy quyền Casso Flow',
  Subscription: 'Gói dịch vụ',
  PlanUpgradeOrder: 'Đơn nâng cấp gói',
  PeriodCharge: 'Phí định kỳ',
  Auth: 'Xác thực',
  Dispute: 'Tranh chấp',
  EmailTemplate: 'Mẫu email',
  INVOICE_IMPORT: 'Nhập hóa đơn',
  CustomerBankAccount: 'Tài khoản ngân hàng KH',
  SmtpConfig: 'Cấu hình SMTP',
  ReceivableBalanceHistory: 'Lịch sử công nợ',
  WebhookInbox: 'Webhook nhận về',
};

export const ACTION_TYPE_LABELS: Record<string, string> = {
  RECEIVABLE_CREATE: 'Tạo khoản phải thu',
  RECEIVABLE_UPDATE: 'Cập nhật khoản phải thu',
  RECEIVABLE_WRITE_OFF: 'Xóa nợ',
  RECEIVABLE_CANCEL: 'Hủy khoản phải thu',
  RECEIVABLE_DISPUTE: 'Tranh chấp khoản phải thu',
  PAYMENT_ALLOCATE: 'Phân bổ thanh toán',
  PAYMENT_ALLOCATE_UNDO: 'Hoàn tác phân bổ',
  REMINDER_POLICY_UPDATE: 'Cập nhật chính sách nhắc',
  BANK_CONNECTION_CREATE: 'Tạo kết nối ngân hàng',
  BANK_CONNECTION_DISCONNECT: 'Ngắt kết nối ngân hàng',
  BANK_CONNECTION_API_KEY_ROTATE: 'Xoay API key ngân hàng',
  BANK_CONNECTION_API_KEY_REVEAL: 'Xem API key ngân hàng',
  SUBSCRIPTION_CHANGE_PLAN: 'Đổi gói dịch vụ',
  PLAN_UPGRADE_ORDER_CREATE: 'Tạo đơn nâng cấp gói',
  PERIOD_CHARGE_CREATE: 'Tạo phí định kỳ',
  PERIOD_CHARGE_PAID: 'Thanh toán phí định kỳ',
  BANK_TRANSACTION_SKIP: 'Bỏ qua giao dịch ngân hàng',
  BANK_TRANSACTION_MARK_PREPAID: 'Đánh dấu đã trả trước',
  AUTH_LOGIN: 'Đăng nhập',
  AUTH_LOGOUT: 'Đăng xuất',
  AUTH_SWITCH_ORGANIZATION: 'Chuyển tổ chức',
  AUTH_FORGOT_PASSWORD: 'Quên mật khẩu',
  AUTH_RESET_PASSWORD: 'Đặt lại mật khẩu',
  DISPUTE_OPEN: 'Mở tranh chấp',
  DISPUTE_RESOLVE: 'Giải quyết tranh chấp',
  EMAIL_TEMPLATE_CREATE: 'Tạo mẫu email',
  EMAIL_TEMPLATE_UPDATE: 'Cập nhật mẫu email',
  EMAIL_TEMPLATE_DELETE: 'Xóa mẫu email',
  EMAIL_TEMPLATE_ATTACHMENT_CREATE: 'Thêm file đính kèm mẫu email',
  EMAIL_TEMPLATE_ATTACHMENT_DELETE: 'Xóa file đính kèm mẫu email',
  INVOICE_IMPORT: 'Nhập hóa đơn',
  CUSTOMER_BANK_ACCOUNT_CREATE: 'Tạo tài khoản ngân hàng KH',
  CUSTOMER_BANK_ACCOUNT_UPDATE: 'Cập nhật tài khoản ngân hàng KH',
  CUSTOMER_BANK_ACCOUNT_DEACTIVATE: 'Vô hiệu tài khoản ngân hàng KH',
  SMTP_CONFIG_SAVE: 'Lưu cấu hình SMTP',
  SMTP_CONFIG_DELETE: 'Xóa cấu hình SMTP',
  RECEIVABLE_BALANCE_HISTORY_EXPORT: 'Xuất lịch sử công nợ',
  WEBHOOK_REPROCESS: 'Xử lý lại webhook',
};

// Field names shown in before/after diffs. Unknown fields retain their raw key
// so audit snapshots stay inspectable as the domain evolves.
export const FIELD_LABELS: Record<string, string> = {
  id: 'Mã hệ thống',
  organizationId: 'Tổ chức',
  customerId: 'Khách hàng',
  invoiceId: 'Hóa đơn',
  receivableId: 'Khoản phải thu',
  paymentId: 'Thanh toán',
  originalAmount: 'Nguyên giá',
  paidAmount: 'Đã thu',
  remainingAmount: 'Còn lại',
  unallocatedAmount: 'Chưa phân bổ',
  allocatedAmount: 'Số tiền phân bổ',
  amount: 'Số tiền giao dịch',
  aiRecommendation: 'Gợi ý đối soát AI',
  bankConnectionId: 'Kết nối ngân hàng',
  bankTransactionId: 'Giao dịch ngân hàng',
  accountNumberMasked: 'Số tài khoản đã che',
  counterpartyAccountNumber: 'Số tài khoản đối ứng',
  counterpartyName: 'Tên người chuyển tiền',
  creditLimit: 'Hạn mức tín dụng',
  confirmedAt: 'Thời điểm xác nhận',
  confirmedByUserId: 'Người xác nhận',
  isActive: 'Trạng thái hoạt động',
  payerName: 'Người chuyển tiền',
  providerTransactionId: 'Mã giao dịch ngân hàng',
  taxAmount: 'Tiền thuế',
  transferContent: 'Nội dung chuyển khoản',
  webhookInboxId: 'Webhook nhận về',
  recommendedReceivableId: 'Khoản phải thu đề xuất',
  confidence: 'Độ tin cậy',
  isCurrent: 'Còn phù hợp',
  totalAmount: 'Tổng tiền',
  dueDate: 'Hạn thanh toán',
  issueDate: 'Ngày phát hành',
  status: 'Trạng thái',
  salesRepresentativeId: 'Nhân viên phụ trách',
  createdAt: 'Ngày tạo',
  updatedAt: 'Ngày cập nhật',
  closedAt: 'Ngày đóng',
  version: 'Phiên bản',
  reason: 'Lý do',
  openedByUserId: 'Người mở',
  resolvedByUserId: 'Người xử lý',
  resolvedAt: 'Ngày xử lý',
  allocatedAt: 'Ngày phân bổ',
  allocatedByUserId: 'Người phân bổ',
  deletedAt: 'Ngày xóa',
  deletedByUserId: 'Người xóa',
  receivedAt: 'Thời điểm nhận',
  sentAt: 'Thời điểm gửi',
  invitedAt: 'Ngày mời',
  expiresAt: 'Ngày hết hạn',
  lastSyncAt: 'Lần đồng bộ gần nhất',
  effectiveAt: 'Thời điểm hiệu lực',
  transactionDateTime: 'Thời điểm giao dịch',
  undoReason: 'Lý do hoàn tác',
};

export const ENTITY_TYPE_OPTIONS = Object.entries(ENTITY_TYPE_LABELS).map(
  ([value, label]) => ({ value, label }),
);

export const ACTION_TYPE_OPTIONS = Object.entries(ACTION_TYPE_LABELS).map(
  ([value, label]) => ({ value, label }),
);
