export enum BalanceHistoryReasonCode {
  RECEIVABLE_CREATED = 'RECEIVABLE_CREATED',
  PAYMENT_ALLOCATED = 'PAYMENT_ALLOCATED',
  PAYMENT_ALLOCATION_UNDONE = 'PAYMENT_ALLOCATION_UNDONE',
  RECEIVABLE_CANCELLED = 'RECEIVABLE_CANCELLED',
  RECEIVABLE_WRITTEN_OFF = 'RECEIVABLE_WRITTEN_OFF',
  ROLLOUT_BASELINE = 'ROLLOUT_BASELINE',
}
